### ISSUE TITLE
Weapons can be placed between spinals

### ISSUE THREAD

**Issue by Zowdie** [treeform/istrolid-bugs#13]
Weapons can be placed and built on anywhere that is registered as a spinal mount, including the unused portions of mounts if two are placed vertically. Weapons placed this way will not actually fire, but will affect ship stats (cost, hp, weight, etc.)

![image](https://user-images.githubusercontent.com/29663889/28002190-cb8f96f6-6500-11e7-9636-e2b62470158c.png)

**Comment by treeform** [comment]
We should fix this.

**Comment by bokken12** [comment]
Fixed
