### ISSUE TITLE
Attacking AI commands are changed into 'faster' after recent patch

### ISSUE THREAD

**Issue by 4headLUL** [treeform/istrolid-bugs#14]
![screen shot 2017-07-21 at 05 11 56](https://user-images.githubusercontent.com/30333555/28448845-3058cd3e-6dd3-11e7-9197-7d61eb8163d2.png)
_(It's supposed to be 'less range than 1300')_

**When it happened to 1 ship with 1 attacking command is fine, however, for a whole fleet, over 80% of the maximum fleet, and over 6 attacking commands per ship is not fine.**

**I know the bug only affect the appearance, ships still work the same way, although it's extremely hard to figure out which command causes the ship to _'run into the enemy'_**

**So, please fix this so our AI can properly run into the enemy.**

**Comment by bokken12** [comment]
That's a visual bug which was fixed in master a long time ago but has yet to be merged into production. Sorry that it's still bothering you but for now the best answer is to wait until that happens.
