### ISSUE TITLE
Sound bars in the settings are extremely finicky to use.

### ISSUE THREAD

**Issue by AeveanLeeow** [treeform/istrolid-bugs#16]
Dragging the bar usually either does very little, nothing, or sets it to maximum or 0 volume. Trying to click to set the volume will usually just set it to maximum or 0.

**Comment by treeform** [comment]
You are right they are kind of wonky. I will look into fixing this.

**Comment by treeform** [comment]
I have fixed this and they will be in the next release. Thank you for reporting the bug.
