### ISSUE TITLE
Broken sound steam version

### ISSUE THREAD

**Issue by gilbzxz** [treeform/istrolid-bugs#17]
everytime i open istrolid all my laptop sound system broke 
i try mute and change sound  to 0 
i try mute both electron on sound mixer
not fixed
here example 
https://cdn.discordapp.com/attachments/231268292667375617/340248914588598283/2017-07-28_05-44-06.flv (Istrolid only)

https://cdn.discordapp.com/attachments/231268292667375617/340249900514148355/2017-07-28_05-49-00.flv (istrolid with dota)
this broken sound affect everything like music or movie 
and it stop after i close istrolid
ps only steam version web version good

**Comment by bokken12** [comment]
What OS are you running?

**Comment by gilbzxz** [comment]
![dell-min](https://user-images.githubusercontent.com/30510770/28704978-3ad28e6c-73a0-11e7-83dd-36c002e873c1.png)

**Comment by treeform** [comment]
This sounds like an OS level issues. Apps should not be able to this. It could be a version of electron I am using. Its a very strange bug.

**Comment by gilbzxz** [comment]
yea i guess so i try on my pc dint have this bug 
my laptop os for some reason has this bug
i guess maybe some malware or maybe virus hit my laptop thats all i can think of 
ps. no need fix i guess this come from me only
