### ISSUE TITLE
Sort Friends

### ISSUE THREAD

**Issue by Zowdie** [treeform/istrolid-bugs#18]
Many players have requested that the friend list be sorted in some way.

The following code will sort the friends list in alphabetical order, putting online friends first so that everyone online appears on the top.

`function sortFriends(){
  friendson = [];
  friendsoff = [];
  for(var i in commander.friends){
    if(commander.friends[i] == true){
      online = [];
      for(var j in chat.players){
        online.push(chat.players[j].name);
      }
      if(online.includes(i)){
        friendson.push(i);
      } else {
        friendsoff.push(i);
      }
    }
  }
  friendson.sort();
  friendsoff.sort();
  commander.friends = new Object();
  for(var i in friendson){
    commander.friends[friendson[i]] = true;
  }
  for(var i in friendsoff){
    commander.friends[friendsoff[i]] = true;
  }
  account.simpleCommander();
  account.rootRealSave();
}`

Example:
![image](https://user-images.githubusercontent.com/29663889/28837954-a73168ac-76bc-11e7-81bc-fd6c2aa73200.png)

Building friends list sorting into the game would be rather nice and convenient to most, and make the friends list a little easier to use. Currently most people decide not to use the friends list for the reason that it is extremely messy.

**Comment by bokken12** [comment]
I feel I should mention that we don't code in javascript so posting snippets can illustrate points but don't spend too much time on them other than that. Anyways we can try to clean the friends list up a little.

**Comment by Zowdie** [comment]
client side?

**Comment by bokken12** [comment]
The javascript you see is compiled coffeescript.

**Comment by Zowdie** [comment]
practically the same thing

**Comment by bokken12** [comment]
That's true, it just means it can't be perfectly copy-pasted too from javascript.

**Comment by bokken12** [comment]
Fixed
