### ISSUE TITLE
Fleet Swap Unsaved

### ISSUE THREAD

**Issue by bokken12** [treeform/istrolid-bugs#2]
When players swap fleets in spectator mode the changes are no longer sent to the server, but if they afterward join a team it will not always update their fleet, leaving them spawning from whatever the server had saved for them. To fix this a fleet update should be sent whenever a player joins a team from spectators.

**Comment by apatarty** [comment]
make when ever someone leaves editing mode or fleet

**Comment by treeform** [comment]
I have a fix for this. Should be released soon. Thank you for reporting the bug.
