### ISSUE TITLE
Client bugs out sometimes during server type switch

### ISSUE THREAD

**Issue by Zowdie** [treeform/istrolid-bugs#20]
Sometimes when the server type is changed without reconnecting, the client side is bugged out. Possible side effects:

- Wrong game type displayed
- Erroneous or missing join team buttons
- 1v1r not starting on join; needing host to start manually

![image](https://user-images.githubusercontent.com/29663889/28903546-7687451a-77d3-11e7-9edb-1a3d830ee41c.png)

Above game is a 2v2, in progress, yet the UI is super bugged out and displays 3v3, as well as join buttons for both teams.

**Comment by q-rtz** [comment]
You might want to mention that you have a rank display script on, if that is the case.

**Comment by Zowdie** [comment]
I am 100% certain that any scripts that I use do not affect this problem; it is universal for everyone.

**Comment by q-rtz** [comment]
No, I meant that those ranks might not have been displayed in a normal client. I was just worried that the presence of the ranks might confuse someone who didn't know that it was possible to make a rank display script.

**Comment by treeform** [comment]
Related to #33
