### ISSUE TITLE
Overkill bug

### ISSUE THREAD

**Issue by astral-carrier** [treeform/istrolid-bugs#30]
There's a bug where when a shot hits a target at the exact moment the target is killed by another shot, it will still dissipate against the target, as if it hit a living unit. As an example, when 2 53-damage plasma shots hit a 40hp fighter at the exact same time, both shots will dissipate, even though only 1 of the shots should've been "used" to kill the fighter.

**Comment by bokken12** [comment]
I would view this as the correct interaction for two shots hitting at the same time rather than as a bug, are there other games that respond differently?

**Comment by treeform** [comment]
This actually a buff to fighters and some thing we want to keep. We tested different overkill strategies and found this to be the best.
