### ISSUE TITLE
Automatic changing of command details when moving attack command above another attack command

### ISSUE THREAD

**Issue by astral-carrier** [treeform/istrolid-bugs#31]
I noticed that almost every time I move an attack command above another attack command in the ai, it will automatically change some detail in the ai command. Some common changes include: 

- Swapping attack types: For example if a ram command was above a kite command, moving the kite command above the ram command will change the kite command to a ram and the ram command to a kite. 

- Swapping stats: Same as the attack commands bug except it affects the stats of the target that the commands are analyzing, instead of the attack type. 

I'm not sure if these are just cosmetic bugs that leave the actual ai unchanged, or if they actually affect the ai. I did notice this one time when I moved an attack command (one with attack type "attack") above a flee command (I wanted to change the attack command to a flee). It automatically changed to flee when I moved it above the other flee command, so I assumed it was flee and left it alone. The next time I checked it had reverted back to attack. 

These can be easily reproduced, but I can attach screenshots if you want.

**Comment by lectrician1** [comment]
Please do @the-non-feline

**Comment by treeform** [comment]
Yeah this was really broken. I have fixed this. Should be in the next version.
