### ISSUE TITLE
Weapon Description Typo

### ISSUE THREAD

**Issue by lectrician1** [treeform/istrolid-bugs#34]
There's a typo in one of the weapon description boxes:
![screenshot 2017-10-19 at 6 22 24 pm](https://user-images.githubusercontent.com/22477298/31799188-470a7b32-b4fe-11e7-9eb9-bf30c8a9f22a.png)

**Comment by Saktoth** [comment]
You are referring to the fact that it adds +15% reload time? That's an addition to reload TIME. Not a faster reload RATE. There is no typo.

**Comment by Saktoth** [comment]
+15% reload time means slower reload. This is correct.

**Comment by Xendergo** [comment]
I think that should be more clear. I thought +15% reload meant reloading 15% faster.
