### ISSUE TITLE
Play vs AI won't load

### ISSUE THREAD

**Issue by lectrician1** [treeform/istrolid-bugs#35]
Play vs AI mode won't load as it is displaying **waiting...** almost every time I try it:
![screenshot 2017-10-19 at 6 54 57 pm](https://user-images.githubusercontent.com/22477298/31799329-0bf056ba-b4ff-11e7-8eb4-914d12f7d017.png)

**Comment by treeform** [comment]
We have reproduced this. Will fix.

**Comment by treeform** [comment]
I have fixed this, will be in the next release. 

Thank you for reporting this!
