### ISSUE TITLE
Able to be placed in 2 battles

### ISSUE THREAD

**Issue by lectrician1** [treeform/istrolid-bugs#36]
One time after becoming disconnected (wifi went down) and reloading the game webpage, I was able to join a new match while in my previous match, I was being shown as inactive on the server on my friend's computer (he was in-battle). I was still able to leave this match and re-join the one I left.

**Comment by Zowdie** [comment]
Not an issue and not related to being disconnected. You can join multiple matches regardless of your connection to the server. You just need to be in one game when it starts and then you're in the the entirety of the game.
