### ISSUE TITLE
Ships left behind when moving groups

### ISSUE THREAD

**Issue by Zowdie** [treeform/istrolid-bugs#4]
Title, when moving a large group of ships a small group may linger behind when the main group finds a new destination.

**Comment by bokken12** [comment]
This issue is hard to duplicate, do you mind giving more information? Is there a good way to replicate this bug? When the ships don't go to their destination does the destination marker stay there or vanish? Is it one command at a time or part of a longer queue?

**Comment by Zowdie** [comment]
It's pretty hard to duplicate - it tends to happen at random. No easy way to replicate on will. Best way is to make a group of fighters and start giving orders, eventually one or two will drop. All of the following ships have been given orders as part of the larger group to travel to a line:
![image](https://user-images.githubusercontent.com/29663889/27511019-86df043c-58ea-11e7-94a4-537c295a137b.png)

Destination marker vanishes on ships left behind.

**Comment by Zowdie** [comment]
Doesn't seem to be related to shift click since most of the times I've encountered (if not all) were normal non shift queued orders. However problem only started after shift click was added.

**Comment by treeform** [comment]
I have managed to replicated. Its a real thing. You just need to click very fast and have many ships.

**Comment by mvollrath** [comment]
I don't click very fast but still experience at least once in most games.

**Comment by bokken12** [comment]
Fixed
