### ISSUE TITLE
2 major issues with the AI attack command

### ISSUE THREAD

**Issue by astral-carrier** [treeform/istrolid-bugs#42]
Since the recent cosmetics update, AI "attack" commands have become broken in 2 major ways: 

1. When the command triggers, it is supposed to make the ship turn to face the enemy that triggered it. This rarely happens now, instead it will usually stop and only stop the ship. 

2. This bug is considerably rarer. Sometimes, the command will make the ship move towards the enemy, even when it doesn't need to, resulting in ships with this command sometimes randomly advancing. This bug sometimes even triggers on enemies outside the command's trigger range. 

As both a "cyborg" and an AI enthusiast, these bugs have hit me hard. Please fix them as soon as possible. Thanks!

**Comment by bokken12** [comment]
Fixed, expect an updated version to be released soon.
