### ISSUE TITLE
AI still freezes

### ISSUE THREAD

**Issue by lectrician1** [treeform/istrolid-bugs#43]
I'm yellow here in the picture below and even after the update, my AI still freezes. I still have to reactivate them by moving my ships around every 2 1/2 minutes. As the game goes on, this can become up to every 10 seconds. 
![screenshot 2017-12-06 at 1 32 50 pm](https://user-images.githubusercontent.com/22477298/33681658-d17134e4-da8a-11e7-8f18-2c92f0134d7e.png)
As you can see in the picture above, they seem to just be sitting in their arc-like position This bug seems to be constant in AIs that have the stay at range command. After a certain amount of time, the ships will stay at range, even though they are set to only stay at range of enemies that are closer than their range.
**Here is my AI:**
![screenshot 2017-12-06 at 1 43 07 pm](https://user-images.githubusercontent.com/22477298/33681954-a5e20942-da8b-11e7-9235-20ed10ff41a9.png)

**Comment by lectrician1** [comment]
By freezes I mean they just don't move.

**Comment by bokken12** [comment]
Fixed in the next tester version, see issue #58.
