### ISSUE TITLE
AI dropdowns resetting to default

### ISSUE THREAD

**Issue by Xendergo** [treeform/istrolid-bugs#44]
The guard command occasionally changes to capture. I hear that happens with other commands too, but I haven't experienced this with other commands.

**Comment by lectrician1** [comment]
Once a single ship of that with the AI is guarding a single capture point, then new ships will seek out a new point to guard.

**Comment by Xendergo** [comment]
I know that, guard in the AI editor actually changes to capture.

**Comment by lectrician1** [comment]
Ok then, so what’s your issue?

**Comment by Xendergo** [comment]
I'm experiencing this with point defense now. But, I set it to guard, I leave the AI menu, open the AI menu, and its set to capture.

**Comment by Xendergo** [comment]
This seems to be fixed, but I'm not sure
