### ISSUE TITLE
Is there a way to code istrolid AI in javascript?

### ISSUE THREAD

**Issue by Xendergo** [treeform/istrolid-bugs#47]
I've seen on the internet and on your discord that you can code Istrolid AI in javascript.
https://gist.github.com/Rio6/52674571657ee5730911b8bff13fa219
I can't find it in any menus, so is this possible and if so, how do you open it?

**Comment by astral-carrier** [comment]
This is not Q&A, it's where you report problems with the game. For questions post on reddit or discord. 

To answer your question, you can press f10 in the Steam app and navigate to "console". Enter Javascript in there. You have to write the code yourself though. You can also do the same in Chrome by using Developer Tools.
