### ISSUE TITLE
recharging bug

### ISSUE THREAD

**Issue by apatarty** [treeform/istrolid-bugs#48]
my ring bomber run out of energy in energy transfer radius, it doesn't recharge, after it i turn it a bit it starts recharging again
![ring bomber glitch](https://user-images.githubusercontent.com/29877932/35781094-754325d0-09b3-11e8-83d1-c588922606aa.PNG)

**Comment by lectrician1** [comment]
I have this as well. Please fix ASAP. It caused me to lose rank.

**Comment by Saktoth** [comment]
Resolved next patch.
