### ISSUE TITLE
AI does not Save when Ships are Spawned

### ISSUE THREAD

**Issue by ghost** [treeform/istrolid-bugs#56]
In design, the ai appears to save and function correctly, however, when the ship is spawned in, it keeps its default command (ex. "Spread to Command Points" would do "Capture Command Points" instead). This has happened multiple times, but if I copy the ship and delete the old one, it seems to be alright.

**Comment by astral-carrier** [comment]
AI does not save until you close the AI editor. This is probably the reason.
