### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Xendergo** [treeform/istrolid-bugs#57]
1. I can't run Istrolid, it says "Failed to connect to main server. Please retry"
2. I open the console and see these errors:
`
WebSocket connection to 'ws://198.199.109.223:88/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by bokken12** [comment]
This error isn't specific enough to pursue, the root server was likely down momentarily. Create a new issue with details on how to reproduce this issue if it is reoccurring.

**Comment by Xendergo** [comment]
It got fixed, I just forgot to close it.
