### ISSUE TITLE
Stay in Range has my ships ram the target in range ship regardless of set range

### ISSUE THREAD

**Issue by ghost** [treeform/istrolid-bugs#58]
Basically, when I have a "Stay in x range of slot y units" and my units leave that designated range, they fly all the way back to the ship rather than just getting back in the range. I'm not sure if this is intended as it did not work like this before.

**Comment by lectrician1** [comment]
See issue #43

**Comment by ghost** [comment]
I'm not sure if it is the same issue, my ships don't freeze, if a higher command is activated after, they still move. It just seemed that they fly all the way to stay in range and not just stopping once in range.

**Comment by bokken12** [comment]
That would be expected. I believe this bug happens infrequently when a dead unit is targeted to stay at range from which would leave the command with precedence over lower AI orders. I have a fix in mind so will try rolling that out to master to be tested in the coming days, hopefully allowing us to close this sand #43

**Comment by bokken12** [comment]
I've committed a fix to master and so am closing this issue unless testing reveals it to still be a problem.
