### ISSUE TITLE
Ship Deletion

### ISSUE THREAD

**Issue by WindigoOfOrange** [treeform/istrolid-bugs#59]
Ship Deletion

During the moment of starting a game, when in the fleet moving menu and holding a ship, the ship will delete itself and isn't locatable after the fact. 

I was in a game, 1v1 with a square when I was moving around my fleet for the impending match. When holding one of my ships and the countdown hit 0, I was kicked out of the fleet swapping menu into the normal game.  When going back in to secure the last ship that I was moving, It was no-where to be found in any of the numerous fleets that I had down. 

-Steps to Reproduce- Be in a 1v1 game, have someone start the game, go into menu after the game tick has started, hold a ship from the 2nd line in the 10th row, move it to a hover over the 1st line, 2nd row.  As the game starts, you'll be kicked out into the normal game window for a battle, go back into the fleet swapping menu and search for said ship. It Isn't there anymore.

The bugs not very often, although I don't usually recall how many times I'm in the fleet swapping menu moving ships when a game starts, the last time I remember losing a ship was a few months back.

**Comment by bokken12** [comment]
Fixed in an external branch
