### ISSUE TITLE
Games in 1v1t after fleetswap do not correctly display fleet

### ISSUE THREAD

**Issue by Jwdegames** [treeform/istrolid-bugs#6]
Along with the fleet not updating, the fleet shown is displayed incorrectly. (Ex: I have  2 fleets - 1 and 2. I'm on fleet 1 and then change to fleet 2 in spectator. When I play though I see the fleet 2 ships but spawn the fleet 1 ships.)

**Comment by bokken12** [comment]
I believe that this is for the same reason as bug #2 not because of 1v1t, marking as a duplicate.

**Comment by treeform** [comment]
I have pushes a fix for this. Should be released soon. Thank you for reporting the bug.
