### ISSUE TITLE
Some swear words unrestricted by the chat

### ISSUE THREAD

**Issue by Xendergo** [treeform/istrolid-bugs#60]
Words like jew are restricted, but words like the F word and S word are unrestricted. Also, jewish, and jews aren't censored, also, jew with any sort of punctuation isn't censored

1. How it affects the game: People can swear, and there are kids playing.
2. A numbered list stating how to reproduce the bug:   1. type a swear word into the chat
3. How often the bug occurs: Always

I recommend this list of swear words to censor, http://www.bannedwordlist.com/lists/swearWords.txt

**Comment by Avamander** [comment]
I recommend nothing is censored. It won't work anyways and is thus a waste of dev time.

**Comment by Xendergo** [comment]
I disagree, no swear words makes it a better experience for everyone, and making the game better means more people will play, which means more people might buy the DLC, which means more money for the devs.

**Comment by Avamander** [comment]
@F4Tornado 
If some swear words make or break your experience then you gotta get a thicker skin in addition to the fact that **swear word filters do not work**.

**Comment by Xendergo** [comment]
1. You don't need to add @F4Tornado to notify me about this
2. They help though
3. Lets *not* start a flame war.
4. It doesn't ruin my experience, I still play Istrolid

**Comment by lectrician1** [comment]
I feel that censoring words is always a pain to the developers. If we
continue to have a stable and considerate community though, people will be
pressured not to swear. If you really want to go into COPPA protection and
stuff, tree could just make it so that chat isn't an option when you are
under 13 (age requirement would be part of the registration process).

**Comment by Xendergo** [comment]
I feel like age restriction would be an even bigger pain to developers, because I know from experience that blocking one word is just as easy as blocking 100, and they've already blocked one.

**Comment by lectrician1** [comment]
No, I said that chat wouldn't be available for those under 13, not that the developers would block words. In other words, there just wouldn't be a chat button.

**Comment by Xendergo** [comment]
That's what I meant by the age restriction.

**Comment by Xendergo** [comment]
Also, I was watching a video, and I got to this part, https://youtu.be/OcPCYswIe2M?t=6m40s

Pretty self explanatory why this is relevant

**Comment by apatarty** [comment]
i feel like people are just going to somehow think of new swear words and slang for them

**Comment by apatarty** [comment]
eventually people are just going to start spamming swear words just to be able to say 'i got around the system, look at me'

**Comment by treeform** [comment]
Sorry not doing anything about this. The problem is toxic players not the words they use. I put minimal number of words I did not like and thats about it.
