### ISSUE TITLE
(AI) More dps then[...]bug misscalculated

### ISSUE THREAD

**Issue by gilbzxz** [treeform/istrolid-bugs#62]
Only work up to 25 more then that can't trigger when it should enemy ship has 400 dps
![moredpsbug](https://user-images.githubusercontent.com/30510770/42157153-81430e46-7e1f-11e8-8249-9458dee2f45c.png)
what make this bug there is miscalculation it calculate like 1x16 
more dps then [26] they only trigger ship with 416+ dps  <---26x16
more dps then [27] -> 432
more dps then [28] -> 448

**Comment by bokken12** [comment]
Fixed in master
