### ISSUE TITLE
AI Wiggles While Attempting Capture Commands (Capture, Spread, etc.)

### ISSUE THREAD

**Issue by ghost** [treeform/istrolid-bugs#67]
AI Wiggles While Attempting Capture Commands (Capture, Spread, etc.)

1. While using the ai capture command on ships along with variations such as spread to, the ship will have a slight wiggle as it approaches both slowing it down and using more energy in the process. I can only imagine it is taxing on the game as well since it must be constantly creating a new movement command for its path. This bug began occurring after the 0.48.3 patch release and likely has something to do with a change made during that patch that was not publicly documented. 
2. Add the capture command to any ship and enter a game with it.
3. Every time the command is used 
4. Revert how the command functioned prior to the 0.48.3 patch update

**Comment by bokken12** [comment]
Resolved in QOL branch
