### ISSUE TITLE
AI Finish player orders command

### ISSUE THREAD

**Issue by ghost** [treeform/istrolid-bugs#68]
https://cdn.discordapp.com/attachments/231268292667375617/542416142967242752/unknown.png
1 When using the Finish Player Orders command after cloak (or someone suggested, any other) command,
2 the ai ignores the previous command although the ship is unselected, rather than waiting for cloak before continuing.
This always occurs (or very rarely doesn't).

**Comment by bokken12** [comment]
Fixed in QOL branch
