### ISSUE TITLE
weapon modules affecting 4 separated spinal mounts (quantum mechanics?)

### ISSUE THREAD

**Issue by ateready** [treeform/istrolid-bugs#69]
Weapon modules affecting 4 separated spinal mounts

Currently I'm experiencing a bug where a ship has a module affect 4 spinal mounts, despite 3 of them not being next to the module. Below is the code for the stripped down ship: shipeyJwYXJ0cyI6W3sicG9zIjpbLTQwLDIwXSwidHlwZSI6IlJlbG9hZGVyTW9kIiwiZGlyIjowfSx7InBvcyI6Wy04MCw0MF0sInR5cGUiOiJNb3VudDEwUmFuZ2UiLCJkaXIiOjB9LHsicG9zIjpbMCw0MF0sInR5cGUiOiJNb3VudDM2MCIsImRpciI6MH0seyJwb3MiOlstMTIwLDYwXSwidHlwZSI6IkJ1bGxldFNwZWVkTW9kIiwiZGlyIjowfSx7InBvcyI6Wy0xMjAsLTIwXSwidHlwZSI6IkJ1bGxldFNwZWVkTW9kIiwiZGlyIjowfSx7InBvcyI6WzQwLDYwXSwidHlwZSI6IlJlbG9hZGVyTW9kIiwiZGlyIjowfSx7InBvcyI6Wy00MCwtNjBdLCJ0eXBlIjoiUmVsb2FkZXJNb2QiLCJkaXIiOjB9LHsicG9zIjpbODAsNDBdLCJ0eXBlIjoiTW91bnQxMFJhbmdlIiwiZGlyIjowfSx7InBvcyI6Wy04MCwtNDBdLCJ0eXBlIjoiTW91bnQxMFJhbmdlIiwiZGlyIjowfSx7InBvcyI6WzgwLC00MF0sInR5cGUiOiJNb3VudDEwUmFuZ2UiLCJkaXIiOjB9LHsicG9zIjpbNDAsLTIwXSwidHlwZSI6IlJlbG9hZGVyTW9kIiwiZGlyIjowfSx7InBvcyI6WzAsNDBdLCJ0eXBlIjoiTWlzc2lsZVR1cnJldCIsImRpciI6MH0seyJwb3MiOlstODAsLTQwXSwidHlwZSI6IkF1dG9UdXJyZXQiLCJkaXIiOjB9LHsicG9zIjpbLTgwLDQwXSwidHlwZSI6IkF1dG9UdXJyZXQiLCJkaXIiOjB9LHsicG9zIjpbODAsNDBdLCJ0eXBlIjoiQXV0b1R1cnJldCIsImRpciI6MH0seyJwb3MiOls4MCwtNDBdLCJ0eXBlIjoiQXV0b1R1cnJldCIsImRpciI6MH1dLCJuYW1lIjoiIiwiYWlSdWxlcyI6W1siRmllbGQgIyB3aGVuIG1vbmV5IG92ZXIgIyBhdCBwcmlvcml0eSAjIiwxLDEwMDAsNF0sWyJXaGVuICMlIG9mIGVuZXJneSwgQGNoYXJnZVR5cGVzIiwzMCwiZmluZCByZWNoYXJnZXIiXSxbIkBhdHRhY2tUeXBlcyBlbmVteSB3aXRoaW4gI20iLCJXaWdnbGUiLDMwMDBdLFsiQGNhcFR5cGVzIGNvbW1hbmQgcG9pbnRzIHdpdGhpbiAjbSIsIkNhcHR1cmUiLDEwMDAwXSxbIkdvdG8gQGxvY2F0aW9uVHlwZXMiLCJlbmVteSBzcGF3biJdXX0=

When removing and replacing the reload module on the bottom right, the stats change for all 4 spinal mounted weapons, despite there being ample space between 3 of them. However, the module on the top right only does 3, while the top left reload module does 1, and the bottom right reload module affects 2. This is weird behaviour and probably should be solved. I tried abusing it, only after realising it makes weapons worse like in the ship down below. Thank you! 
(2nd ship code) : 
shipeyJwYXJ0cyI6W3sicG9zIjpbMTIwLDBdLCJ0eXBlIjoiQnVsbGV0U3BlZWRNb2QiLCJkaXIiOjB9LHsicG9zIjpbNDAsLTEyMF0sInR5cGUiOiJXaW5nMngyIiwiZGlyIjowfSx7InBvcyI6WzEyMCw0MF0sInR5cGUiOiJCdWxsZXRTcGVlZE1vZCIsImRpciI6MH0seyJwb3MiOlstMTIwLDgwXSwidHlwZSI6IkJ1bGxldFNwZWVkTW9kIiwiZGlyIjowfSx7InBvcyI6WzAsNjBdLCJ0eXBlIjoiTW91bnQzNjAiLCJkaXIiOjB9LHsicG9zIjpbNDAsMTIwXSwidHlwZSI6Ik1vdW50MzYwIiwiZGlyIjowfSx7InBvcyI6Wy00MCwxMjBdLCJ0eXBlIjoiTW91bnQzNjAiLCJkaXIiOjB9LHsicG9zIjpbLTQwLDE1MF0sInR5cGUiOiJIQXJtb3IyeDEiLCJkaXIiOjB9LHsicG9zIjpbLTcwLDE1MF0sInR5cGUiOiJIQXJtb3IxeDFBbmdsZSIsImRpciI6MH0seyJwb3MiOls0MCwxNTBdLCJ0eXBlIjoiSEFybW9yMngxIiwiZGlyIjowfSx7InBvcyI6WzEyMCw4MF0sInR5cGUiOiJCdWxsZXRTcGVlZE1vZCIsImRpciI6MH0seyJwb3MiOlstODAsNjBdLCJ0eXBlIjoiTW91bnQxMFJhbmdlIiwiZGlyIjowfSx7InBvcyI6WzAsMTAwXSwidHlwZSI6IlRhcmdldGluZ01vZCIsImRpciI6MH0seyJwb3MiOls3MCwxNTBdLCJ0eXBlIjoiSEFybW9yMXgxQW5nbGUiLCJkaXIiOjB9LHsicG9zIjpbLTgwLC0yMF0sInR5cGUiOiJNb3VudDEwUmFuZ2UiLCJkaXIiOjB9LHsicG9zIjpbODAsLTIwXSwidHlwZSI6Ik1vdW50MTBSYW5nZSIsImRpciI6MH0seyJwb3MiOls4MCw2MF0sInR5cGUiOiJNb3VudDEwUmFuZ2UiLCJkaXIiOjB9LHsicG9zIjpbLTEyMCwtNDBdLCJ0eXBlIjoiQnVsbGV0U3BlZWRNb2QiLCJkaXIiOjB9LHsicG9zIjpbMCwtMTAwXSwidHlwZSI6IkVuZ2luZTA5IiwiZGlyIjowfSx7InBvcyI6Wy00MCwtNzBdLCJ0eXBlIjoiQmF0dGVyeTJ4MSIsImRpciI6MH0seyJwb3MiOlstODAsLTgwXSwidHlwZSI6IkVuZ2luZTA5IiwiZGlyIjowfSx7InBvcyI6Wy04MCwxMjBdLCJ0eXBlIjoiSEFybW9yMngyQW5nbGUiLCJkaXIiOjB9LHsicG9zIjpbODAsLTgwXSwidHlwZSI6IkVuZ2luZTA5IiwiZGlyIjowfSx7InBvcyI6Wy0xMjAsNDBdLCJ0eXBlIjoiQnVsbGV0U3BlZWRNb2QiLCJkaXIiOjB9LHsicG9zIjpbLTEwLC0zMF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbMCwtNjBdLCJ0eXBlIjoiQmF0dGVyeTJ4MiIsImRpciI6MH0seyJwb3MiOlsxMCwtMTBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6WzEwLC0zMF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbLTEwLC0xMF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbLTExMCwxMTBdLCJ0eXBlIjoiSEFybW9yMXgxQW5nbGUiLCJkaXIiOjB9LHsicG9zIjpbLTUwLC05MF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbLTExMCwtNzBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6Wy00MCwtMTIwXSwidHlwZSI6IldpbmcyeDIiLCJkaXIiOjB9LHsicG9zIjpbLTMwLC05MF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbMTIwLC00MF0sInR5cGUiOiJCdWxsZXRTcGVlZE1vZCIsImRpciI6MH0seyJwb3MiOls4MCwxMjBdLCJ0eXBlIjoiSEFybW9yMngyQW5nbGUiLCJkaXIiOjB9LHsicG9zIjpbMTEwLDExMF0sInR5cGUiOiJIQXJtb3IxeDFBbmdsZSIsImRpciI6MH0seyJwb3MiOls0MCwtNzBdLCJ0eXBlIjoiQmF0dGVyeTJ4MSIsImRpciI6MH0seyJwb3MiOlszMCwtOTBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6WzExMCwtNzBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6WzUwLC05MF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbMCwyMF0sInR5cGUiOiJUYXJnZXRpbmdNb2QiLCJkaXIiOjB9LHsicG9zIjpbLTEyMCwwXSwidHlwZSI6IkJ1bGxldFNwZWVkTW9kIiwiZGlyIjowfSx7InBvcyI6WzQwLC00MF0sInR5cGUiOiJEYW1wZW5lck1vZCIsImRpciI6MH0seyJwb3MiOls0MCwwXSwidHlwZSI6IlJlbG9hZGVyTW9kIiwiZGlyIjowfSx7InBvcyI6WzQwLDQwXSwidHlwZSI6IlJlbG9hZGVyTW9kIiwiZGlyIjowfSx7InBvcyI6WzQwLDgwXSwidHlwZSI6IkRhbXBlbmVyTW9kIiwiZGlyIjowfSx7InBvcyI6Wy00MCwwXSwidHlwZSI6IlJlbG9hZGVyTW9kIiwiZGlyIjowfSx7InBvcyI6Wy00MCw0MF0sInR5cGUiOiJSZWxvYWRlck1vZCIsImRpciI6MH0seyJwb3MiOlstNDAsLTQwXSwidHlwZSI6IkRhbXBlbmVyTW9kIiwiZGlyIjowfSx7InBvcyI6Wy00MCw4MF0sInR5cGUiOiJEYW1wZW5lck1vZCIsImRpciI6MH0seyJwb3MiOlstMTMwLC03MF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbLTExMCwtOTBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6WzExMCwtOTBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6WzEzMCwtNzBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6Wy0xMCwxNTBdLCJ0eXBlIjoiU2hpZWxkR2VuMXgxIiwiZGlyIjowfSx7InBvcyI6WzEwLDE1MF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbLTEwLDEzMF0sInR5cGUiOiJTaGllbGRHZW4xeDEiLCJkaXIiOjB9LHsicG9zIjpbMTAsMTMwXSwidHlwZSI6IlNoaWVsZEdlbjF4MSIsImRpciI6MH0seyJwb3MiOls0MCwxMjBdLCJ0eXBlIjoiUERUdXJyZXQiLCJkaXIiOjB9LHsicG9zIjpbLTQwLDEyMF0sInR5cGUiOiJQRFR1cnJldCIsImRpciI6MH0seyJwb3MiOlswLDYwXSwidHlwZSI6Ik1pc3NpbGVUdXJyZXQiLCJkaXIiOjB9LHsicG9zIjpbODAsNjBdLCJ0eXBlIjoiQm9tYkd1biIsImRpciI6MH0seyJwb3MiOlstODAsNjBdLCJ0eXBlIjoiQm9tYkd1biIsImRpciI6MH0seyJwb3MiOlstODAsLTIwXSwidHlwZSI6IkJvbWJHdW4iLCJkaXIiOjB9LHsicG9zIjpbODAsLTIwXSwidHlwZSI6IkJvbWJHdW4iLCJkaXIiOjB9XSwibmFtZSI6IiIsImFpUnVsZXMiOltbIkZpZWxkICMgd2hlbiBtb25leSBvdmVyICMgYXQgcHJpb3JpdHkgIyIsMSwxMDAwLDRdLFsiV2hlbiAjJSBvZiBlbmVyZ3ksIEBjaGFyZ2VUeXBlcyIsMzAsImZpbmQgcmVjaGFyZ2VyIl0sWyJAYXR0YWNrVHlwZXMgZW5lbXkgd2l0aGluICNtIiwiV2lnZ2xlIiwzMDAwXSxbIkBjYXBUeXBlcyBjb21tYW5kIHBvaW50cyB3aXRoaW4gI20iLCJDYXB0dXJlIiwxMDAwMF0sWyJHb3RvIEBsb2NhdGlvblR5cGVzIiwiZW5lbXkgc3Bhd24iXV19

**Comment by bokken12** [comment]
That was a fun puzzle. As it turns out the individual module was not affecting all four weapons, just that their automatic sorting caused it to appear that way. When the module was removed the highest DPS auto cannon became the lowest DPS, shifting every other weapon up by one, and making it look like every one had a stat change despite three of the four being the same just in different locations.
