### ISSUE TITLE
Orange Background Too Bright

### ISSUE THREAD

**Issue by Zowdie** [treeform/istrolid-bugs#8]
The bright orange background that is sometimes seen during games (example can be seen in the background of the Curves and Shadows banner) is excessively bright and not only does it not fit the current theme of duller pleasing to see backgrounds but it hurts your eyes. Ideally this background should be removed or made a lot duller.

**Comment by q-rtz** [comment]
Saktoth has already commented about this ingame, and stated that he has reduced the saturation of the orange.
